version: '3.3'

volumes:
  postgres_data:
  back_static:
  front_static:
  media_volume:

services:
  db:
    image: postgres:13.10
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: alphasn/foodgram_backend
    env_file:
      - .env
    volumes:
      - back_static:/backend_static
      - media_volume:/app/media
    depends_on:
      - db

  frontend:
    image: alphasn/foodgram_frontend
    volumes:
      - front_static:/result_build
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    ports:
      - 9000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - front_static:/frontend_static
      - back_static:/backend_static
      - media_volume:/media
    depends_on:
      - backend
