version: '3.7'

volumes:
  postgres_data:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.10
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    image: alphasn/foodgram_backend
    env_file:
      - .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/app/media/
    depends_on:
      - db

  frontend:
    image: alphasn/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
    depends_on:
      - db

  nginx:
    image: nginx:1.25.2
    network_mode: "host"
    ports:
      - 9000:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html
      - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
      - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
    depends_on:
      - backend
